//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication21
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.helps = new HashSet<help>();
            this.med_order = new HashSet<med_order>();
        }
    
        public int customer_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string customer_uname { get; set; }
        public string address { get; set; }
        public string customer_pw { get; set; }
        public string secqn { get; set; }
        public string secans { get; set; }
        public string dob { get; set; }
        public string gender { get; set; }
        public string contactno { get; set; }
        public string emailid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<help> helps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<med_order> med_order { get; set; }
    }
}
