//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication21
{
    using System;
    using System.Collections.Generic;
    
    public partial class med_order
    {
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string med_id { get; set; }
        public Nullable<int> amount { get; set; }
        public string mode_of_payment { get; set; }
        public string order_date { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
